import type { Driver } from './Drivers/Driver'
import type { BindingValues } from './Query/Builder'

import { Connection, type ConnectionConfig } from './Connection'

export class MySqlConnection extends Connection {
  /**
  * The last inserted ID generated by the server.
  *
  * @var string|int|null
  */
  protected lastInsertId: string | number | undefined

  constructor (
    driver: Driver,
    database: string = '',
    tablePrefix: string = '',
    config: ConnectionConfig = {}
  ) {
    super(driver, database, tablePrefix, config)
  }

  /**
 * Get the connection's last insert ID.
 *
 * @return string|int|null
 */
  public getLastInsertId (): string | number | undefined {
    return this.lastInsertId
  }

  /**
   * Run an insert statement against the database.
   *
   * @param  string  $query
   * @param  array  $bindings
   * @param  string|null  $sequence
   * @return bool
   */
  public override async insert (
    query: string,
    bindings: BindingValues = [],
    sequence?: string
  ): Promise<boolean> {
    return await this.run<boolean>(query, bindings, async (
      query: string,
      bindings: BindingValues
    ): Promise<boolean> => {
      if (this.pretending()) {
        return true
      }

      const statement = this.getDriver().prepare(query)

      this.bindValues(statement, this.prepareBindings(bindings))

      this.recordsHaveBeenModified()

      const result = await statement.execute(bindings)

      this.lastInsertId = this.getDriver().lastInsertId(sequence)

      return result
    })
  }
}
