import { Str } from "../Support";
import { Connection } from "./Connection";
import { Driver } from "./Drivers";
import type { Bindings } from "./Query";
import { MySqlGrammar as QueryGrammar } from "./Query";

export class MySqlConnection extends Connection {
  /**
   * The last inserted ID generated by the server.
   *
   * @var string|int|null
   */
  protected lastInsertId?: string | number;

  /**
   * {@inheritdoc}
   */
  public getDriverTitle() {
    return this.isMaria() ? 'MariaDB' : 'MySQL';
  }

  /**
   * Run an insert statement against the database.
   *
   * @param  string  $query
   * @param  array  $bindings
   * @param  string|null  $sequence
   * @return bool
   */
  override public insert(query: string, bindings: Bindings = {}, sequence?: string) {
    return this.run(query, bindings, (query: string, bindings: Bindings) => {
      if (this.pretending()) {
        return true;
      }

      const statement = this.getDriver().prepare(query);

      this.bindValues(statement, this.prepareBindings(bindings));

      this.recordsHaveBeenModified();

      const result = statement.execute();

      this.lastInsertId = this.getDriver().lastInsertId(sequence);

      return result;
    });
  }

  /**
   * Escape a binary value for safe SQL embedding.
   *
   * @param  string  $value
   * @return string
   */
  protected escapeBinary(value) {
    const hex = bin2hex(value);

    return `x'${hex}'`;
  }

  /**
   * Determine if the given database exception was caused by a unique constraint violation.
   *
   * @param  \Exception  $exception
   * @return bool
   */
  override protected isUniqueConstraintError(exception: Error): boolean {
    return exception.message.match('#Integrity constraint violation: 1062#i') !== null
  }

  /**
   * Extract the index that caused a unique constraint violation.
   *
   * @param  Exception  $exception
   * @return array{index: string|null, columns: list<string>}
   */
  protected parseUniqueConstraintViolation(exception: Error): {
    index: string | null;
    columns: string[];
  } {
    const matches = exception.message.match(
      /Duplicate entry '.*?' for key '(?:.*?\.)?(.+?)'/i,
    );

    return {
      columns: [],
      index: matches?.[1] ?? null,
    };
  }

  /**
   * Get the connection's last insert ID.
   *
   * @return string|int|null
   */
  public getLastInsertId() {
    return this.lastInsertId;
  }

  /**
   * Determine if the connected database is a MariaDB database.
   *
   * @return bool
   */
  public isMaria() {
    return this.getDriver().getAttribute(Driver.ATTR_SERVER_VERSION).includes('MariaDB');
  }

  /**
   * Get the server version for the connection.
   *
   * @return string
   */
  override public getServerVersion(): string {
    const version = super.getServerVersion()

    return version.includes('MariaDB')
      ? Str.between(version, '5.5.5-', '-MariaDB')
            : version;
  }

  /**
   * Get the default query grammar instance.
   *
   * @return \Illuminate\Database\Query\Grammars\MySqlGrammar
   */
  override protected getDefaultQueryGrammar() {
    return new QueryGrammar(this);
  }

  /**
   * Get a schema builder instance for the connection.
   *
   * @return \Illuminate\Database\Schema\MySqlBuilder
   */
  public getSchemaBuilder() {
    if (is_null(this.schemaGrammar)) {
      this.useDefaultSchemaGrammar();
    }

    return new MySqlBuilder($this);
  }

  /**
   * Get the default schema grammar instance.
   *
   * @return \Illuminate\Database\Schema\Grammars\MySqlGrammar
   */
  protected getDefaultSchemaGrammar() {
    return new SchemaGrammar($this);
  }

  /**
   * Get the schema state for the connection.
   *
   * @param  \Illuminate\Filesystem\Filesystem|null  $files
   * @param  callable|null  $processFactory
   * @return \Illuminate\Database\Schema\MySqlSchemaState
   */
  public getSchemaState(?Filesystem $files = null, ?callable $processFactory = null) {
    return new MySqlSchemaState($this, $files, $processFactory);
  }

  /**
   * Get the default post processor instance.
   *
   * @return \Illuminate\Database\Query\Processors\MySqlProcessor
   */
  protected getDefaultPostProcessor() {
    return new MySqlProcessor;
  }
}
